name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - uses: actions/checkout@v3

      - name: Upgrade pip
        run: |
          pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install cml==0.7.4

      - name: Train Model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python train.py
          echo "Model Accuracy: 0.89" > metrics.txt

      - name: Generate Report
        run: |
          echo "## Model Report" > report.md
          cat metrics.txt >> report.md
          cml comment create report.md --token ${{ secrets.GITHUB_TOKEN }}
