name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y git
          pip install -r requirements.txt cml

      - name: Run Training
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python train.py
          echo "MODEL METRICS" > metrics.txt
          echo "Accuracy: 0.89" >> metrics.txt

      - name: Report Results
        run: |
          echo "## Model Report" > report.md
          cat metrics.txt >> report.md
          cml comment create report.md --token ${{ secrets.GITHUB_TOKEN }}
